version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=spoilme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    build: "./services/spoilme-backend/"
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=(Host(`staging.spoilme.shop`)&&PathPrefix(`/api`))
      - traefik.http.routers.backend.priority=2
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=letsEncrypt
    depends_on:
      - db
  frontend:
    build: "./services/spoilme-frontend/"
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=(Host(`staging.spoilme.shop`)&&PathPrefix(`/`))
      - traefik.http.routers.frontend.priority=1
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=letsEncrypt
  reverse-proxy:
    image: traefik:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
      - ./acme.json:/acme.json
