version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=spoilme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: "./services/spoilme-backend/"
    labels:
      - traefik.http.routers.backend.rule=(Host(`staging.spoilme.shop`) && Path(`/api`))
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=letsEncrypt
    depends_on:
      - db
  frontend:
    build: "./services/spoilme-frontend/"
    labels:
      - traefik.http.routers.frontend.rule=Host(`staging.spoilme.shop`)
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=letsEncrypt
  reverse-proxy:
    image: traefik:latest
    network_mode: host
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
